### ISSUE TITLE
depstar tips

### ISSUE THREAD

**Issue by practicalli-john** [practicalli/blog#41]

**Comment by jr0cket** [comment]
# Ahead of time compilation
is there an equivalent of lein's :java-source-paths for deps.edn?

We use depstar at work to build uberjars for production deployment and we do not AOT anything. 

AOTing is not recommended anymore unless you deeply care about startup perf

Thanks for replying @seancorfield. Along with deploying our uberjar to ECS within a docker image, we also invoke it multiple times within our CI pipeline. My principle motivation was to shave some time off the CI runs, and additionally plain curiosity around why the facility wasn't being supported yet.

Fair enough. If you (manually) create a classes folder in your project and add it as an :extra-paths entry when building your uberjar, you can run clojure -e "(compile,'my.entry.point)" as a way to compile the entry namespace (my.entry.point here) and its transitive deps.

depstar tries hard to avoid messing with your project or your classpath: it just packages up whatever you tell it to, using the classpath as constructed by clojure using whatever options you've provided. Because compile requires that classes exists -- or else you can use binding to tell the compiler to put class files somewhere else, that must still exist -- and that the output path of the compiler needs to be on the classpath for depstar to include those files, it just doesn't seem like something depstar itself should try to do.

Note that the depstar README does address this case https://github.com/seancorfield/depstar in terms of Main-Class in the manifest but it stops short of explaining specifically how to compile code and get the classes onto your classpath.

**Comment by seancorfield** [comment]
As noted in the README, I specifically avoid giving explicit steps on how to do this because I don't want to encourage it but a pair of commands like the following should work (assuming you're building an `api` project with `api.main/-main` in it, and you have an alias for `:uberjar` -- and you have a `pom.xml` file!):

```bash
clojure -e "((requiring-resolve,'clojure.java.shell/sh),\"mkdir\",\"classes\")" \
        -e "(compile,'api.main)" \
        -e "(shutdown-agents)"
clojure -Sdeps '{:aliases,{:classes,{:extra-paths,["classes"]}}}' \
        -A:classes:uberjar api-standalone.jar
```
You can simplify that by manually creating `classes` yourself -- and then you won't need the `java.shell` (or `shutdown-agents`) options. And you could add that `:extra-paths ["classes"]` to your `:uberjar` alias...

**Comment by seancorfield** [comment]
Given `depstar` has been archived (and it long since added support for AOT directly anyway), this issue should probably be closed out.

**Comment by seancorfield** [comment]
*Bump!*

Can we close this issue out?
